// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function ParseCsv(arg1:string):Promise<Array<main.Transaction>>;

export function ParseTransactionsRange(arg1:Array<main.Transaction>,arg2:string,arg3:string):Promise<Array<main.Transaction>>;
