// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearTransactionsTable() {
  return window['go']['main']['App']['ClearTransactionsTable']();
}

export function GetCategoryTotals(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetCategoryTotals'](arg1, arg2, arg3, arg4);
}

export function GetTotalSpending() {
  return window['go']['main']['App']['GetTotalSpending']();
}

export function GetTransactions() {
  return window['go']['main']['App']['GetTransactions']();
}

export function GetTransactionsRange(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTransactionsRange'](arg1, arg2, arg3, arg4);
}

export function InsertTransaction(arg1) {
  return window['go']['main']['App']['InsertTransaction'](arg1);
}

export function InsertTransactions(arg1) {
  return window['go']['main']['App']['InsertTransactions'](arg1);
}

export function ParseCsv(arg1) {
  return window['go']['main']['App']['ParseCsv'](arg1);
}

export function ParseTransactionsRange(arg1, arg2) {
  return window['go']['main']['App']['ParseTransactionsRange'](arg1, arg2);
}
